autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 1

service:
  type: ClusterIP
  protocol: TCP
  port: 8001

image:
  repository: "${DOCKER_IMAGE}"
  pullPolicy: Always
  tag: ${IMAGE_TAG}

imagePullSecrets:
  - name: javelin-registry-secret

resources:
  requests:
    memory: 512Mi
    cpu: 100m
  limits:
    memory: 1024Mi
    cpu: 500m

secrets:
  enabled: true
  secretData:
    HF_TOKEN: '${HF_TOKEN}'
    DB_USERNAME: '${DB_USERNAME}'
    DB_PASSWORD: '${DB_PASSWORD}'
    DB_HOST: '${DB_HOST}'
    DB_SSL_MODE: 'require'
    REDIS_CONN_STR: '${REDIS_CONN_STR}'
    # REDIS_CACERT: '/app/certs/redis-ca.pem'
    MODEL_HIGH_END: 'azure/gpt-4o'
    MODEL_LOW_END: 'azure/gpt35'
    # # openai
    # OPENAI_API_KEY: '${OPENAI_API_KEY}'
    # GROK_MODEL: grok-3
    # XAI_API_KEY: '${XAI_API_KEY}'
    # azure
    AZURE_API_KEY: '${AZURE_API_KEY}'
    AZURE_API_BASE: '${AZURE_API_BASE}'
    AZURE_API_VERSION: '${AZURE_API_VERSION}'
    EMBEDDING_MODEL: text-embedding-3-small

# volumes:
#   - name: redis-cert-volume
#     secret:
#       secretName: javelin-redteam-redis-cert
#       optional: false

# volumeMounts:
#   - name: redis-cert-volume
#     mountPath: "/app/certs/redis-ca.pem"
#     readOnly: true
#     subPath: redis-ca.pem

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kube/nodegroup
          operator: In
          values:
          - general

worker:
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1024Mi
      cpu: 1000m

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kube/nodegroup
            operator: In
            values:
            - general

seederJob:
  enabled: true

  secretsSeederSpecific:
    enabled: true
    secretData:
      REDTEAM_SEEDER_DATASET: "javelinai/javelin-red5-with-embeddings"
      REDTEAM_SEEDER_DATASET_VER: "spg_v1"
      REDTEAM_SEEDER_ARGS: ""

  resources:
    requests:
      memory: 1Gi
      cpu: 2000m
    limits:
      memory: 2Gi
      cpu: 3000m