ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP 
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/group.order: '1000'

    alb.ingress.kubernetes.io/load-balancer-name: ${k8s_cluster_name}-alb-ingress
    alb.ingress.kubernetes.io/group.name: ${k8s_cluster_name}-group
    alb.ingress.kubernetes.io/subnets: ${public_subnet_ids}
    alb.ingress.kubernetes.io/certificate-arn: ${acm_certificate_arn}
    alb.ingress.kubernetes.io/security-groups: ${alb_security_group_ids}
  hosts:
    - host: dummy.example.com
      paths:
        - path: /
          serviceName: dummy
          servicePort: 3000
          pathType: Prefix