global:
  leaderElection:
    namespace: ${namespace}
installCRDs: true

resources: 
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 125m
    memory: 512Mi

webhook:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 125m
      memory: 512Mi

cainjector:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 125m
      memory: 512Mi

startupapicheck:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 125m
      memory: 512Mi