{
 "title": "kubernetes Deployment Dashboard Overall",
 "description": "Deployment",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "Cluster", "query": "label_values(k8scluster)" },
   {
    "name": "Namespace",
    "query": "label_values(kube_namespace_labels{k8scluster=\"$Cluster\"}, namespace)"
   },
   {
    "name": "Deployment",
    "query": "label_values(kube_deployment_created{k8scluster=\"$Cluster\",namespace=\"$Namespace\"},deployment)"
   },
   {
    "name": "Node",
    "query": "label_values(kube_node_created{k8scluster=\"$Cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment Available Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",deployment=~\"^$Deployment$\"}) / sum(kube_deployment_status_replicas{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",deployment=~\"^$Deployment$\"}) * 100",
     "query": "sum(kube_deployment_status_replicas_available{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",deployment=~\"^$Deployment$\"}) / sum(kube_deployment_status_replicas{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",deployment=~\"^$Deployment$\"}) * 100",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Pod Available Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod=~\"^$Deployment.*$\",phase=\"Running\"}) / sum(kube_pod_status_phase{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod=~\"^$Deployment.*$\"}) * 100",
     "query": "sum(kube_deployment_status_replicas_available{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",deployment=~\"^$Deployment$\"}) / sum(kube_deployment_status_replicas{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",deployment=~\"^$Deployment$\"}) * 100",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Container Available Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod=~\"^$Deployment.*$\"}) / (sum(kube_pod_container_status_running{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod=~\"^$Deployment.*$\"}) + sum(kube_pod_container_status_terminated{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod=~\"^$Deployment.*$\"}) + sum(kube_pod_container_status_waiting{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod=~\"^$Deployment.*$\"})) * 100",
     "query": "sum(kube_deployment_status_replicas_available{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",deployment=~\"^$Deployment$\"}) / sum(kube_deployment_status_replicas{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",deployment=~\"^$Deployment$\"}) * 100",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",deployment=~\"^$Deployment$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",deployment=~\"^$Deployment$\"})"
    }
   ]
  },
  {
   "title": "Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod=~\"^$Deployment.*$\",phase=\"Running\"})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod=~\"^$Deployment.*$\",phase=\"Failed\"})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod=~\"^$Deployment.*$\",phase=\"Pending\"})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Unknown",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod=~\"^$Deployment.*$\",phase=\"Unknown\"})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod=~\"^$Deployment.*$\"})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Terminated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod=~\"^$Deployment.*$\",reason!=\"Completed\"})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Waiting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod=~\"^$Deployment.*$\"})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Restarts（30m）",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod=~\"^$Deployment.*$\"}[30m]))",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod_name=~\"^$Deployment.*$\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod_name=~\"^$Deployment.*$\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod_name=~\"^$Deployment.*$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\",k8scluster=~\"^$Cluster$\"})  * 100"
    }
   ]
  },
  {
   "title": "CPU usage (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod_name=~\"^$Deployment.*$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\",k8scluster=~\"^$Cluster$\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod_name=~\"^$Deployment.*$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod_name=~\"^$Deployment.*$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 18 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\",k8scluster=~\"^$Cluster$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod_name=~\"^$Deployment.*$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\",k8scluster=~\"^$Cluster$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 18 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\",pod_name=~\"^$Deployment.*$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\",k8scluster=~\"^$Cluster$\"})"
    }
   ]
  }
 ]
}