fullnameOverride: "javelin-redteam-lab1"

service:
  type: ClusterIP
  protocol: TCP
  port: 8002

livenessProbe:
  httpGet:
    path: /v1/redteam/lab1/health
    port: 8002
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 2
readinessProbe:
  httpGet:
    path: /v1/redteam/lab1/health
    port: 8002
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 2

image:
  repository: "${DOCKER_IMAGE}"
  pullPolicy: Always
  tag: ${IMAGE_TAG}

imagePullSecrets:
  - name: javelin-registry-secret

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 1024Mi
    cpu: 500m

secrets:
  enabled: true
  secretData:
    AZURE_API_KEY: '${AZURE_API_KEY}'
    AZURE_API_BASE: '${AZURE_API_BASE}'
    AZURE_API_VERSION: '${AZURE_API_VERSION}'
    OPENAI_MODEL_LOW: gpt-3.5-turbo
    AZURE_MODEL: azure/gpt35
    BEDROCK_MODEL: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
    BEDROCK_REGION: us-east-1
    BEDROCK_BEARER_TOKEN: '${BEDROCK_BEARER_TOKEN}'
    BEDROCK_ACCESS_KEY: '${BEDROCK_ACCESS_KEY}'
    OPENAI_API_KEY_1: '${OPENAI_API_KEY_1}'
    OPENAI_API_KEY_2: '${OPENAI_API_KEY_2}'
    OPENAI_API_KEY_3: '${OPENAI_API_KEY_3}'
    LOCAL_API_KEY: '${LOCAL_API_KEY}'
    DEFAULT_PROVIDER: '${DEFAULT_PROVIDER}'

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kube/nodegroup
          operator: In
          values:
          - general

secretsApiSpecific:
  enabled: false

worker:
  enabled: false

seederJob:
  enabled: false