name: CICD Auto Release - Javelin IaC

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**/*CHANGELOG.md"

jobs:
  reusable-workflow:
    permissions:
      contents: 'write'
      id-token: 'write'
    uses: getjavelin/javelin-workflow/.github/workflows/workflow-auto-release.yml@main
    secrets:
      DEVOPS_GITHUB_TOKEN: ${{ secrets.DEVOPS_GITHUB_TOKEN }}